#-------------------------------
# Site Settings
title: Yukio Nozawa
description: Portfolio of Yukio Nozawa, a programmer / game designer / sound designer.
logo: "/images/logo.svg" # You can add own logo. For example "/images/logo.svg".
logo_dark: "/images/logo-dark.svg"
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Projects"
      url: "/projects/"
    - title: "Posts"
      url: "/posts/"
    - title: "Resources"
      submenu:
      - url: "/posts/sns"
        title: "Social media"
    - title: "About Me"
      url: "/about/"

# Call to action button
cta_button:
  enable: true
  cta_button_link: '/contact/'
  cta_button_text: Get in touch


#-------------------------------
# Author Settings
author:
  author_name: "Yukio Nozawa"
  author_avatar: "/images/01-1.jpg"


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: ソフトウェアエンジニア / ゲームデザイナー / サウンドデザイナー
  hero_description: 自由奔放な全盲のコード書き。それ以外にもだいたいなんでもやります。

# Hero Logos
hero_logos:
  enable: false

#-------------------------------
# Slider Featured Settings
featured:
  enable: false
  featured_title: Selected Work


#-------------------------------
# Projects Section Settings
projects:
  enable: true
  projects_title: Recent Work
  projects_description:


#-------------------------------
# Testimonials Section Settings
testimonials:
  enable: false

#-------------------------------
# Faq (Frequently asked questions) Settings
faq:
  enable: false
  faq_title: Frequently asked questions
  faq_intro: Need some answers?


#-------------------------------
# Blog Section Settings
blog:
  enable: true
  blog_intro: What’s new?
  blog_title: Latest from blog


#-------------------------------
# Author Section Settings
author_section:
  enable: true
  author_section_title: "ようこそ！野澤幸男(別名 cat)のホームページです。"
  author_section_description: 人生の目標は、猫のように自由に生きることです。
  author_section_image: "/images/01.jpg"
  author_section_image_alt: 正面から撮影した本人
  author_section_button_text: お気軽にご連絡ください！
  author_section_button_link: "/contact/"


#-------------------------------
# Footer Settings

# Footer Navigation
footer_menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Posts'
      url: '/posts/'
    - url: '/about/'
      title: 'About Me'

# Social Links
social:
- {icon: "fa-brands fa-facebook-f", name: "Facebook", link: "https://facebook.com"}
- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://twitter.com"}
- {icon: "fa-brands fa-github", name: "GitHub", link: "https://github.com/yncat/"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: false


#-------------------------------
# Contact Settings
contact:
  email: lp@nyanchangames.com # Add your form_id
  description: Yukio cat Nozawa へのお問い合わせはこちらからどうぞ！


#-------------------------------
# Comment Section (Disqus)
disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id