#-------------------------------
# Site Settings
title: Yukio cat Nozawa
description: Portfolio of Yukio Nozawa (also known as cat), a programmer / game designer / sound designer.
logo: "/images/logo.gif" # You can add own logo. For example "/images/logo.svg".
logo_dark: "/images/logo-dark.gif"
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.

# Site Settings (English)
title_en: Yukio cat Nozawa
description_en: Portfolio of Yukio Nozawa (also known as cat), a programmer / game designer / sound designer.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      title_en: "Home"
      url: "/"
      url_en: "/en/"
    - title: "Projects"
      title_en: "Projects"
      url: "/projects/"
      url_en: "/en/projects/"
    - title: "Posts"
      title_en: "Posts"
      url: "/posts/"
      url_en: "/en/posts/"
    - title: "websites"
      title_en: "Websites"
      url: "/websites/"
      url_en: "/en/websites/"
    - title: "Media"
      title_en: "Media"
      url: "/media/"
      url_en: "/en/media/"
    - title: "About Me"
      title_en: "About Me"
      url: "/about/"
      url_en: "/en/about/"

# Call to action button
cta_button:
  enable: true
  cta_button_link: '/contact/'
  cta_button_text: Contact


#-------------------------------
# Author Settings
author:
  author_name: "Yukio Nozawa"
  author_avatar: "/images/author.jpg"


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: A software engineer, game designer and sound designer
  hero_title_en: A software engineer, game designer and sound designer
  hero_description: 自由奔放な全盲のコード書き。それ以外にもだいたいなんでもやります。
  hero_description_en: A free-spirited blind coder. I do pretty much everything else too.

# Hero Logos
hero_logos:
  enable: false

#-------------------------------
# Slider Featured Settings
featured:
  enable: false
  featured_title: Selected Work


#-------------------------------
# Projects Section Settings
projects:
  enable: true
  projects_title: 活動
  projects_title_en: Activities
  projects_description: これまで行った活動を紹介します。
  projects_description_en: Here are the activities I have been involved in.


#-------------------------------
# websites Section Settings
media:
  enable: true
  media_title: 関連サイト
  media_description: 私が関わっている関連サイトを紹介します。


#-------------------------------
# media Section Settings
media:
  enable: true
  media_title: 記事掲載情報
  media_description: 過去に掲載された記事を紹介します


#-------------------------------
# Testimonials Section Settings
testimonials:
  enable: false

#-------------------------------
# Faq (Frequently asked questions) Settings
faq:
  enable: false
  faq_title: Frequently asked questions
  faq_intro: Need some answers?


#-------------------------------
# Blog Section Settings
blog:
  enable: true
  blog_intro: What's new?
  blog_intro_en: What's new?
  blog_title: 最新ブログ投稿
  blog_title_en: Latest Blog Posts

#-------------------------------
# Related Posts Section Settings
related_posts:
  related_posts_intro: Related Posts
  related_posts_intro_en: Related Posts
  related_posts_title: 読み逃した記事はありませんか
  related_posts_title_en: In case you missed it


#-------------------------------
# Author Section Settings
author_section:
  enable: true
  author_section_title: "野澤幸男(別名 cat)のホームページです。"
  author_section_title_en: "This is Yukio Nozawa's (a.k.a. cat) homepage."
  author_section_description: 人生の目標は、猫のように自由に生きることです。
  author_section_description_en: My life goal is to live freely like a cat.
  author_section_image: "/images/cat_headphones.gif"
  author_section_image_alt: 猫がヘッドフォンを付けて音楽に乗っている
  author_section_image_alt_en: A cat wearing headphones and grooving to music
  author_section_button_text: お気軽にご連絡ください！
  author_section_button_text_en: Feel free to contact me!
  author_section_button_link: "contact/"
  author_section_button_link_en: "/en/contact/"


#-------------------------------
# Footer Settings

# Footer Navigation
footer_menu__settings:
  menu__items:
    - title: 'Home'
      title_en: 'Home'
      url: '/'
      url_en: '/en/'
    - title: 'Projects'
      title_en: 'Projects'
      url: '/projects/'
      url_en: '/en/projects/'
    - title: 'Posts'
      title_en: 'Posts'
      url: '/posts/'
      url_en: '/en/posts/'
    - title: "websites"
      title_en: "Websites"
      url: "/websites/"
      url_en: "/en/websites/"
    - title: "Media"
      title_en: "Media"
      url: "/media/"
      url_en: "/en/media/"
    - title: 'About Me'
      title_en: 'About Me'
      url: '/about/'
      url_en: '/en/about/'

# Social Links
social:
- {icon: "fa-brands fa-twitter", name: "Twitter", link: "https://twitter.com/nyanchan2013"}
- {icon: "fa-brands fa-github", name: "GitHub", link: "https://github.com/yncat/"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: false


#-------------------------------
# Contact Settings
contact:
  email: mnqewlpb
  description: お問い合わせはこちらからどうぞ！
  description_en: Please feel free to contact me!


#-------------------------------
# Comment Section (Disqus)
disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google_analytics: G-CPSKDY9S64