#-------------------------------
# Site Settings
title: Yukio cat Nozawa
description: Portfolio of Yukio Nozawa (also known as cat), a programmer / game designer / sound designer.
logo: "/images/logo.gif" # You can add own logo. For example "/images/logo.svg".
logo_dark: "/images/logo-dark.gif"
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Projects"
      url: "/projects/"
    - title: "Posts"
      url: "/posts/"
    - title: "websites"
      url: "/websites/"
    - title: "Media"
      url: "/media/"
    - title: "About Me"
      url: "/about/"

# Call to action button
cta_button:
  enable: true
  cta_button_link: '/contact/'
  cta_button_text: お問い合わせ


#-------------------------------
# Author Settings
author:
  author_name: "Yukio Nozawa"
  author_avatar: "images/author.jpg"


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: A software engineer, game designer and sound designer
  hero_description: 自由奔放な全盲のコード書き。それ以外にもだいたいなんでもやります。

# Hero Logos
hero_logos:
  enable: false

#-------------------------------
# Slider Featured Settings
featured:
  enable: false
  featured_title: Selected Work


#-------------------------------
# Projects Section Settings
projects:
  enable: true
  projects_title: 活動
  projects_description: これまで行った活動を紹介します。


#-------------------------------
# websites Section Settings
media:
  enable: true
  media_title: 関連サイト
  media_description: 私が関わっている関連サイトを紹介します。


#-------------------------------
# media Section Settings
media:
  enable: true
  media_title: 記事掲載情報
  media_description: 過去に掲載された記事を紹介します


#-------------------------------
# Testimonials Section Settings
testimonials:
  enable: false

#-------------------------------
# Faq (Frequently asked questions) Settings
faq:
  enable: false
  faq_title: Frequently asked questions
  faq_intro: Need some answers?


#-------------------------------
# Blog Section Settings
blog:
  enable: true
  blog_intro: What’s new?
  blog_title: 最新ブログ投稿


#-------------------------------
# Author Section Settings
author_section:
  enable: true
  author_section_title: "ようこそ！野澤幸男(別名 cat)のホームページです。"
  author_section_description: 人生の目標は、猫のように自由に生きることです。
  author_section_image: "images/cat_headphones.gif"
  author_section_image_alt: 猫がヘッドフォンを付けて音楽に乗っている
  author_section_button_text: お気軽にご連絡ください！
  author_section_button_link: "/contact/"


#-------------------------------
# Footer Settings

# Footer Navigation
footer_menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Posts'
      url: '/posts/'
    - url: '/about/'
      title: 'About Me'

# Social Links
social:
- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://twitter.com/nyanchan2013"}
- {icon: "fa-brands fa-github", name: "GitHub", link: "https://github.com/yncat/"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: false


#-------------------------------
# Contact Settings
contact:
  email: lp@nyanchangames.com # Add your form_id
  description: Yukio cat Nozawa へのお問い合わせはこちらからどうぞ！


#-------------------------------
# Comment Section (Disqus)
disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id